// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// Source: trigger.proto

package pb

import (
	context "context"
	transport "github.com/erda-project/erda-infra/pkg/transport"
	grpc1 "github.com/erda-project/erda-infra/pkg/transport/grpc"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion5

// CmsServiceClient is the client API for CmsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CmsServiceClient interface {
	RunPipelinesByTrigger(ctx context.Context, in *PipelineTriggerRequest, opts ...grpc.CallOption) (*PipelineTriggerResponse, error)
}

type cmsServiceClient struct {
	cc grpc1.ClientConnInterface
}

func NewCmsServiceClient(cc grpc1.ClientConnInterface) CmsServiceClient {
	return &cmsServiceClient{cc}
}

func (c *cmsServiceClient) RunPipelinesByTrigger(ctx context.Context, in *PipelineTriggerRequest, opts ...grpc.CallOption) (*PipelineTriggerResponse, error) {
	out := new(PipelineTriggerResponse)
	err := c.cc.Invoke(ctx, "/erda.core.pipeline.cms.CmsService/RunPipelinesByTrigger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CmsServiceServer is the server API for CmsService service.
// All implementations should embed UnimplementedCmsServiceServer
// for forward compatibility
type CmsServiceServer interface {
	RunPipelinesByTrigger(context.Context, *PipelineTriggerRequest) (*PipelineTriggerResponse, error)
}

// UnimplementedCmsServiceServer should be embedded to have forward compatible implementations.
type UnimplementedCmsServiceServer struct {
}

func (*UnimplementedCmsServiceServer) RunPipelinesByTrigger(context.Context, *PipelineTriggerRequest) (*PipelineTriggerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunPipelinesByTrigger not implemented")
}

func RegisterCmsServiceServer(s grpc1.ServiceRegistrar, srv CmsServiceServer, opts ...grpc1.HandleOption) {
	s.RegisterService(_get_CmsService_serviceDesc(srv, opts...), srv)
}

var _CmsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "erda.core.pipeline.cms.CmsService",
	HandlerType: (*CmsServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "trigger.proto",
}

func _get_CmsService_serviceDesc(srv CmsServiceServer, opts ...grpc1.HandleOption) *grpc.ServiceDesc {
	h := grpc1.DefaultHandleOptions()
	for _, op := range opts {
		op(h)
	}

	_CmsService_RunPipelinesByTrigger_Handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.RunPipelinesByTrigger(ctx, req.(*PipelineTriggerRequest))
	}
	var _CmsService_RunPipelinesByTrigger_info transport.ServiceInfo
	if h.Interceptor != nil {
		_CmsService_RunPipelinesByTrigger_info = transport.NewServiceInfo("erda.core.pipeline.cms.CmsService", "RunPipelinesByTrigger", srv)
		_CmsService_RunPipelinesByTrigger_Handler = h.Interceptor(_CmsService_RunPipelinesByTrigger_Handler)
	}

	var serviceDesc = _CmsService_serviceDesc
	serviceDesc.Methods = []grpc.MethodDesc{
		{
			MethodName: "RunPipelinesByTrigger",
			Handler: func(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
				in := new(PipelineTriggerRequest)
				if err := dec(in); err != nil {
					return nil, err
				}
				if interceptor == nil && h.Interceptor == nil {
					return srv.(CmsServiceServer).RunPipelinesByTrigger(ctx, in)
				}
				if h.Interceptor != nil {
					ctx = context.WithValue(ctx, transport.ServiceInfoContextKey, _CmsService_RunPipelinesByTrigger_info)
				}
				if interceptor == nil {
					return _CmsService_RunPipelinesByTrigger_Handler(ctx, in)
				}
				info := &grpc.UnaryServerInfo{
					Server:     srv,
					FullMethod: "/erda.core.pipeline.cms.CmsService/RunPipelinesByTrigger",
				}
				return interceptor(ctx, in, info, _CmsService_RunPipelinesByTrigger_Handler)
			},
		},
	}
	return &serviceDesc
}
